<?php

return [
    ['name' => 'Genesis', 'abbreviation' => 'gn', 'testament' => 'old', 'chapters_count' => 50],
    ['name' => 'Exodo', 'abbreviation' => 'ex', 'testament' => 'old', 'chapters_count' => 40],
    ['name' => 'Levitico', 'abbreviation' => 'lv', 'testament' => 'old', 'chapters_count' => 27],
    ['name' => 'Numeros', 'abbreviation' => 'nm', 'testament' => 'old', 'chapters_count' => 36],
    ['name' => 'Deuteronomio', 'abbreviation' => 'dt', 'testament' => 'old', 'chapters_count' => 34],
    ['name' => 'Josue', 'abbreviation' => 'js', 'testament' => 'old', 'chapters_count' => 24],
    ['name' => 'Juizes', 'abbreviation' => 'jz', 'testament' => 'old', 'chapters_count' => 21],
    ['name' => 'Rute', 'abbreviation' => 'rt', 'testament' => 'old', 'chapters_count' => 4],
    ['name' => '1 Samuel', 'abbreviation' => '1sm', 'testament' => 'old', 'chapters_count' => 31],
    ['name' => '2 Samuel', 'abbreviation' => '2sm', 'testament' => 'old', 'chapters_count' => 24],
    ['name' => '1 Reis', 'abbreviation' => '1rs', 'testament' => 'old', 'chapters_count' => 22],
    ['name' => '2 Reis', 'abbreviation' => '2rs', 'testament' => 'old', 'chapters_count' => 25],
    ['name' => '1 Cronicas', 'abbreviation' => '1cr', 'testament' => 'old', 'chapters_count' => 29],
    ['name' => '2 Cronicas', 'abbreviation' => '2cr', 'testament' => 'old', 'chapters_count' => 36],
    ['name' => 'Esdras', 'abbreviation' => 'ed', 'testament' => 'old', 'chapters_count' => 10],
    ['name' => 'Neemias', 'abbreviation' => 'ne', 'testament' => 'old', 'chapters_count' => 13],
    ['name' => 'Ester', 'abbreviation' => 'et', 'testament' => 'old', 'chapters_count' => 10],
    ['name' => 'Jo', 'abbreviation' => 'jo', 'testament' => 'old', 'chapters_count' => 42],
    ['name' => 'Salmos', 'abbreviation' => 'sl', 'testament' => 'old', 'chapters_count' => 150],
    ['name' => 'Proverbios', 'abbreviation' => 'pv', 'testament' => 'old', 'chapters_count' => 31],
    ['name' => 'Eclesiastes', 'abbreviation' => 'ec', 'testament' => 'old', 'chapters_count' => 12],
    ['name' => 'Canticos', 'abbreviation' => 'ct', 'testament' => 'old', 'chapters_count' => 8],
    ['name' => 'Isaias', 'abbreviation' => 'is', 'testament' => 'old', 'chapters_count' => 66],
    ['name' => 'Jeremias', 'abbreviation' => 'jr', 'testament' => 'old', 'chapters_count' => 52],
    ['name' => 'Lamentacoes', 'abbreviation' => 'lm', 'testament' => 'old', 'chapters_count' => 5],
    ['name' => 'Ezequiel', 'abbreviation' => 'ez', 'testament' => 'old', 'chapters_count' => 48],
    ['name' => 'Daniel', 'abbreviation' => 'dn', 'testament' => 'old', 'chapters_count' => 12],
    ['name' => 'Oseias', 'abbreviation' => 'os', 'testament' => 'old', 'chapters_count' => 14],
    ['name' => 'Joel', 'abbreviation' => 'jl', 'testament' => 'old', 'chapters_count' => 3],
    ['name' => 'Amos', 'abbreviation' => 'am', 'testament' => 'old', 'chapters_count' => 9],
    ['name' => 'Obadias', 'abbreviation' => 'ob', 'testament' => 'old', 'chapters_count' => 1],
    ['name' => 'Jonas', 'abbreviation' => 'jn', 'testament' => 'old', 'chapters_count' => 4],
    ['name' => 'Miqueias', 'abbreviation' => 'mq', 'testament' => 'old', 'chapters_count' => 7],
    ['name' => 'Naum', 'abbreviation' => 'na', 'testament' => 'old', 'chapters_count' => 3],
    ['name' => 'Habacuque', 'abbreviation' => 'hc', 'testament' => 'old', 'chapters_count' => 3],
    ['name' => 'Sofonias', 'abbreviation' => 'sf', 'testament' => 'old', 'chapters_count' => 3],
    ['name' => 'Ageu', 'abbreviation' => 'ag', 'testament' => 'old', 'chapters_count' => 2],
    ['name' => 'Zacarias', 'abbreviation' => 'zc', 'testament' => 'old', 'chapters_count' => 14],
    ['name' => 'Malaquias', 'abbreviation' => 'ml', 'testament' => 'old', 'chapters_count' => 4],
    ['name' => 'Mateus', 'abbreviation' => 'mt', 'testament' => 'new', 'chapters_count' => 28],
    ['name' => 'Marcos', 'abbreviation' => 'mc', 'testament' => 'new', 'chapters_count' => 16],
    ['name' => 'Lucas', 'abbreviation' => 'lc', 'testament' => 'new', 'chapters_count' => 24],
    ['name' => 'Joao', 'abbreviation' => 'joa', 'testament' => 'new', 'chapters_count' => 21],
    ['name' => 'Atos', 'abbreviation' => 'at', 'testament' => 'new', 'chapters_count' => 28],
    ['name' => 'Romanos', 'abbreviation' => 'rm', 'testament' => 'new', 'chapters_count' => 16],
    ['name' => '1 Corintios', 'abbreviation' => '1co', 'testament' => 'new', 'chapters_count' => 16],
    ['name' => '2 Corintios', 'abbreviation' => '2co', 'testament' => 'new', 'chapters_count' => 13],
    ['name' => 'Galatas', 'abbreviation' => 'gl', 'testament' => 'new', 'chapters_count' => 6],
    ['name' => 'Efesios', 'abbreviation' => 'ef', 'testament' => 'new', 'chapters_count' => 6],
    ['name' => 'Filipenses', 'abbreviation' => 'fp', 'testament' => 'new', 'chapters_count' => 4],
    ['name' => 'Colossenses', 'abbreviation' => 'cl', 'testament' => 'new', 'chapters_count' => 4],
    ['name' => '1 Tessalonicenses', 'abbreviation' => '1ts', 'testament' => 'new', 'chapters_count' => 5],
    ['name' => '2 Tessalonicenses', 'abbreviation' => '2ts', 'testament' => 'new', 'chapters_count' => 3],
    ['name' => '1 Timoteo', 'abbreviation' => '1tm', 'testament' => 'new', 'chapters_count' => 6],
    ['name' => '2 Timoteo', 'abbreviation' => '2tm', 'testament' => 'new', 'chapters_count' => 4],
    ['name' => 'Tito', 'abbreviation' => 'tt', 'testament' => 'new', 'chapters_count' => 3],
    ['name' => 'Filemom', 'abbreviation' => 'fm', 'testament' => 'new', 'chapters_count' => 1],
    ['name' => 'Hebreus', 'abbreviation' => 'hb', 'testament' => 'new', 'chapters_count' => 13],
    ['name' => 'Tiago', 'abbreviation' => 'tg', 'testament' => 'new', 'chapters_count' => 5],
    ['name' => '1 Pedro', 'abbreviation' => '1pe', 'testament' => 'new', 'chapters_count' => 5],
    ['name' => '2 Pedro', 'abbreviation' => '2pe', 'testament' => 'new', 'chapters_count' => 3],
    ['name' => '1 Joao', 'abbreviation' => '1jo', 'testament' => 'new', 'chapters_count' => 5],
    ['name' => '2 Joao', 'abbreviation' => '2jo', 'testament' => 'new', 'chapters_count' => 1],
    ['name' => '3 Joao', 'abbreviation' => '3jo', 'testament' => 'new', 'chapters_count' => 1],
    ['name' => 'Judas', 'abbreviation' => 'jd', 'testament' => 'new', 'chapters_count' => 1],
    ['name' => 'Apocalipse', 'abbreviation' => 'ap', 'testament' => 'new', 'chapters_count' => 22],
];
